print("Bhanu Mounika")
print("Bhanu Mounika")
print("Bhanu Mounika")
print("Bhanu Mounika")
print("Bhanu Mounika")
print("BITS-Hyderabad")
print("BITS-Hyderabad")
print("BITS-Hyderabad")
print("BITS-Hyderabad")
print("BITS-Hyderabad")